version: '3.8'
services:
  users-posts-postgres-db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    networks:
      - users-posts-postgres-db-bridge
    volumes:
      - users-posts-postgres-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  users-posts-postgres-db:

networks:
  users-posts-postgres-db-bridge:
    driver: bridge
    name: users-posts-postgres-db-bridge