version: '3.8'
services:
  user-posts-postgres-test-db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - user-posts-postgres-test-db:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  user-posts-postgres-test-db: